version: "3.8"

services:
  db:
    container_name: "chirpy"
    image: postgres:13-alpine
    volumes:
      - "./database/postgres-data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    restart: unless-stopped
